# on:
#   push:
#     branches:
#       - new_Design
# name: Build and Release
# jobs:
#   build:
#     # if: steps.semantic.outputs.new-release-published == 'true'
#     runs-on: ubuntu-latest
#     name: Build app
#     steps:
#       - uses: actions/checkout@v3
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.3.0"
#           channel: "stable"
#       - run: flutter --version
#       - run: flutter pub get
#       - run: flutter build apk --split-per-abi --no-shrink --build-name=${{ github.ref }}
#       - run: flutter pub get
#       - run: flutter build appbundle
#   github_release:
#     # if: steps.semantic.outputs.new-release-published == 'true'
#     runs-on: ubuntu-latest
#     name: Release on github
#     steps:
#       - uses: ncipollo/release-action@v1
#         with:
#           release-version: ${{ github.ref }}
#           prerelease: true
#           name: msm-v${{ github.ref }}
#           artifacts: "build/app/outputs/apk/release/*.apk"
#           # bodyFile: "CHANGELOG.md"
#           token: ${{ secrets.TOKEN }}
