on: push
name: Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.13+hotfix.7"
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          name: msmv0.8.3
          artifacts: "build/app/outputs/apk/release/*.apk"
          bodyFile: "release.md"
          token: ${{ secrets.TOKEN }}
